name: Exawind-Manager Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-docs
  cancel-in-progress: true

jobs:
  Docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Dependencies
        run: |
          sudo apt-get update
          python3 -m pip install --upgrade pip
          pip3 install sphinx sphinx_rtd_theme myst-parser
      - name: Build
        run: |
          echo "::add-matcher::.github/problem-matchers/sphinx.json"
          sphinx-build -M html ./docs ./build_docs/manual 2>&1 | tee -a build-output.txt
          mv ./build_docs/manual/html ./documentation
          touch ./documentation/.nojekyll
      - name: Report
        run: |
          echo "::add-matcher::.github/problem-matchers/sphinx.json"
          egrep "WARNING:|Warning:|warning:|ERROR:|Error:|error:" build-output.txt | sort | uniq | \
            awk 'BEGIN{i=0}{print $0}{i++}END{print "Warnings: "i}' > build-output-warnings.txt
          cat build-output-warnings.txt
          exit $(tail -n 1 build-output-warnings.txt | awk '{print $2}')
      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          branch: gh-pages
          folder: documentation
          single-commit: true
